### ISSUE TITLE
@dopt/react BLOCK_API_TYPES missing types

### ISSUE THREAD

**Issue by cooperda00** [dopt/odopt#1100]
# @dopt/react BLOCK_API_TYPES missing types

![Screenshot 2024-01-31 at 13 04 41](https://github.com/dopt/odopt/assets/41230997/d1c288c3-a0f2-4779-a54f-d49a29340d42)

Version 4.1.0 

The union is missing 'hints', 'hintItem', 'block' as block types.

**Comment by joemckenney** [comment]
@cooperda00 thanks for the issue.  I believe I understand why this happened.  Fixing now.

Just so I make sure the fix is complete, how did this issue manifest for you?

**Comment by cooperda00** [comment]
@joemckenney thanks for the quick turnaround. See the snippets below for how it affected me.

![Screenshot 2024-01-31 at 16 27 53](https://github.com/dopt/odopt/assets/41230997/2addd04b-1bba-4010-ac55-379ab0d0f034)
![Screenshot 2024-01-31 at 16 28 01](https://github.com/dopt/odopt/assets/41230997/642b81a9-72d2-459d-996d-e9ec0792a2be)

**Comment by joemckenney** [comment]
@joemckenney  Thanks for the info. This breakage makes sense. 

I just published a new version [@dopt/react@4.1.1 ](https://www.npmjs.com/package/@dopt/react/v/4.1.1) that should fix this issue.
