### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by nipunn1313** [dopt/odopt#1249]
Hi,

I noticed that you don't have a LICENSE at the top of your repo. Would you be willing to add one?

Also noticed that many of the package.json use MIT license, but some of them (eg @dopt/block-api-types, @dopt/react-portal, @dopt/react-utilities, @dopt/semantic-data-layer-checklist, @dopt/semantic-data-layer-tour) don't have a license specified.

IIUC, If there's no license specified, then the code is copyrighted and isn't really good to be used by other projects.

**Comment by joemckenney** [comment]
Fixed w/ https://github.com/dopt/odopt/commit/35b9f548feb2145b9046044029f124f0c0184302 and https://github.com/dopt/odopt/commit/990c106596927b12f898251bfb4fed02d54d8125.
