### ISSUE TITLE
Error trying to install @dopt/javascript

### ISSUE THREAD

**Issue by NLegendre** [dopt/odopt#782]
Hello,
I tried to install the javascript lib with npm.
I've got this error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dopt%2fsemantic-data-layer-card - Not found
npm ERR! 404
npm ERR! 404  '@dopt/semantic-data-layer-card@1.0.0' is not in this registry.
```
Can you have a look ? (maybe a misconfiguration on npmjs.org)

**Comment by joemckenney** [comment]
Hey @NLegendre, could you give installation another try.  We recently published some package dependencies and I forgot to make those public. I just updated everything. I should work now

**Comment by NLegendre** [comment]
Yes it works :)
Thanks!
